### ISSUE TITLE
Settling down

### ISSUE THREAD

**Issue by jan-glx** [LTLA/basilisk#11]
Hi @LTLA,
I got the impression that recirculate will always run python in the very same process as the R session and therefore can never guarantee to work with a conda environment as long as the R process was started in that environment (since the LD_LIBRARY_PATH of a running process cant be changed), while basilisk is running everything python in a separate process and can thus work with any environment. Is this correct? And can I safely depend on basilisk (not asking for legal guarantees here :P)?
best,
Jan

**Comment by LTLA** [comment]
That's more or less correct. The only thing I would add is that **basilisk** will attempt to run its Python in the current R process, for efficiency. If it cannot do so, only then it will start a separate R process; slower, but at least it won't crash.

This behavior has a few interesting implications. For example, while **basilisk** cannot be easily broken by other processes that load in Python, it itself will happily break those processes in return. You can make **basilisk** be "exceptionally polite" by setting `setBasiliskShared(FALSE)` (I think, I can't remember the exact name of that function) in which case it will always start a new R process to do any Python-related task. This will force it to behave with other, less-safe things that use Python.

**Comment by jan-glx** [comment]
Thanks for clarifying! (And the package obviously).
I'd leave this open as it might help others but feel free to close.
