### ISSUE TITLE
Status of basilisk on 32-bit Windows

### ISSUE THREAD

**Issue by hpages** [LTLA/basilisk#12]
Hi Aaron,

I get this error on 32-bit Windows for some unit tests in **HDF5Array** that use `zellkonverter::writeH5AD()`:

> ERROR in test_CSR_H5ADMatrixSeed: Error : Your current architecture is 32bit; however,
> this version of Python was compiled for 64bit.

Full report: https://bioconductor.org/checkResults/3.13/bioc-LATEST/HDF5Array/riesling1-checksrc.html

The error occurs in the call to `zellkonverter::writeH5AD()` which IIUC relies on the miniconda installation that gets automatically installed by **basilisk**.

I was wondering if this is expected, in which case, I can just skip these tests on 32-bit Windows, not a big deal (and I've heard that the R/CRAN folks are considering dropping support for 32-bit Windows for R 4.2 anyways).

Just wanted to check with you before I do that.

Thanks,
H.

**Comment by LTLA** [comment]
Yes, that's right. I never even tried to get 32-bit Windows support for the entire Conda chain, it was just too much - so skip away.

**Comment by hpages** [comment]
Oh I see the `.BBSoptions` file in **basilisk** with the `UnsupportedPlatforms: win32` line in it now. Didn't occur to me to check that first. Thanks for clarifying.

I realize now that we also need to make sure that any package that has a hard dep (direct or indirect) on **basilisk** is marked as unsupported on win32. (**HDF5Array** is _not_ one of them: **basilisk** is only a soft dep for **HDF5Array**, via **zellkonverter** which is suggested and used in some unit tests and maybe some examples.)
