### ISSUE TITLE
How to update an existing basilisk environment

### ISSUE THREAD

**Issue by keller-mark** [LTLA/basilisk#14]
If I change the package list for an environment in `basilisk.R`, how do I tell basilisk to update that environment?

Outside of basilisk I would run `conda env update -f environment.yml`, is there an equivalent basilisk function?

**Comment by LTLA** [comment]
If you're inside a package: the environment should auto-update if you bump your package's version number. Or specifically, it'll create a new environment while marking the old environment for (eventual) deletion. It doesn't update the same environment in place just in case you have multiple R processes and some of them are still using the old environment.
