### ISSUE TITLE
choose python version

### ISSUE THREAD

**Issue by karltayeb** [LTLA/basilisk#19]
Is there a way to specify a specific version of python for a Basilisk environemnt?
`BasiliskEnvironment` doesn't seem to have an argument for this. I thought maybe I could specify python version in the `packages` argument but  passing `packages=c('python==3.8.3, ...)` yields an error.

**Comment by LTLA** [comment]
Hm. **basilisk** should have pulled it out of your `packages`, see

https://github.com/LTLA/basilisk/blob/e5bc4babd9069bd8cc2741eafa5a8e0ac72ed018/R/setupBasiliskEnv.R#L82-L84

What's the error?

**Comment by karltayeb** [comment]
You're right, it seems to be working now. Not sure what I did wrong before.
