### ISSUE TITLE
The environment variable `PIP_USER=true` leads to incorrect installations

### ISSUE THREAD

**Issue by mtmorgan** [LTLA/basilisk#27]
The report at https://github.com/rstudio/reticulate/issues/1209 show that the environment variable `PIP_USER=true` causes `pip install` to install packages into the user rather than conda library. While the user might be instructed not to set, or to override, that variable, this can be complicated in some environments, and anyway basilisk can I believe be made robust to this setting in the same way that reticulate has been. The solution is to add `--no-user` to `pip install` commands, I think at https://github.com/LTLA/basilisk/blob/453ef4be98176bf50bf9005c073bf113dc95e1fa/R/setupBasiliskEnv.R#L100 and https://github.com/LTLA/basilisk/blob/453ef4be98176bf50bf9005c073bf113dc95e1fa/R/setupBasiliskEnv.R#L109 I am not familiar enough with basilisk to provide a simple reproducible example.

**Comment by LTLA** [comment]
Done, thanks.
