### ISSUE TITLE
typo in test-install.R

### ISSUE THREAD

**Issue by vjcitn** [LTLA/basilisk#33]
https://github.com/LTLA/basilisk/blob/4413e51367823198838c6ae2a0e16694b430b67e/tests/testthat/test-install.R#L60 

the test should be for "test_dummy" not "test-dummy"

**Comment by LTLA** [comment]
Interesting. This was not a typo in the past, as the test was passing until recently. IIRC python considers `_` and `-` to be interchangeable; I assume that previous builds of **miniconda** (or maybe **reticulate**) were replacing `_` with `-` as part of some normalization, and this is no longer the case... who knows.
